apiVersion: v1
kind: Template
metadata:
  name: node-pipeline
  annotations:
    openshift.io/display-name: Node.js Pipeline
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-pipeline
  spec:
    source:
      git:
        uri: "https://github.com/leandroberetta/openshift-cicd-demo.git"
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: ${PARAM_APP_NAME}
        - name: IMAGE_NAME
          value: ${PARAM_APP_NAME}
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: GIT_BRANCH
          value: ${PARAM_GIT_BRANCH}
        - name: BASE_IMAGE
          value: nodejs:10
        - name: ARTIFACTS_DIR
          value: ./
        - name: JENKINS_AGENT
          value: nodejs
        - name: COMPILE_COMMANDS
          value: none
        - name: TEST_COMMANDS
          value: none
        - name: CODE_ANALYSIS_COMMANDS
          value: none
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
parameters:
- description: The application name
  displayName: Application Name
  name: PARAM_APP_NAME
  required: true
- description: The Git repository
  displayName: Git Repository
  name: PARAM_GIT_REPO
  required: true
- description: The Git branch
  displayName: Git Branch
  name: PARAM_GIT_BRANCH
  required: true
  value: master
- description: A secret string used to configure the webhook
  displayName: Webhook Secret
  name: PARAM_WEBHOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{40}"